### ISSUE TITLE
index.d.ts找不到Body

### ISSUE THREAD

**Issue by kianfang** [tencentyun/cos-nodejs-sdk-v5#108]
### 执行tsc报类型错误
![image](https://user-images.githubusercontent.com/16569491/122500311-26e76b80-d025-11eb-91c9-5a7491964264.png)

### 1831行的Body类型找不到
![image](https://user-images.githubusercontent.com/16569491/122500329-2f3fa680-d025-11eb-9a54-6be2fb23b70d.png)

### 版本2.9.20，如下图
![image](https://user-images.githubusercontent.com/16569491/122500346-3666b480-d025-11eb-8944-6ada0e4c2d37.png)

**Comment by waiwaiku** [comment]
[#L1831](https://github.com/tencentyun/cos-nodejs-sdk-v5/blob/f5a06474a551c6a9a41f261b41d1dc1c7f26c9c5/index.d.ts#L1831)

**Comment by waiwaiku** [comment]
### 兼容解决方案
> 在`tsconfig.ts`配置的lib补充DOM库
![image](https://user-images.githubusercontent.com/16569491/122504217-682f4980-d02c-11eb-9dca-3102088a3f29.png)

**Comment by haishangfeng** [comment]
我是执行gulp时报此错误。按楼上的指示，打包没报错了。
