### ISSUE TITLE
read ECONNRESET at TLSWrap.onStreamRead(internal/stream_base_commons.js:209:20)

### ISSUE THREAD

**Issue by doujinlan** [tencentyun/cos-nodejs-sdk-v5#113]
read ECONNRESET at TLSWrap.onStreamRead(internal/stream_base_commons.js:209:20)

**Comment by carsonxu** [comment]
试试：new COS({ KeepAlive: false });

**Comment by doujinlan** [comment]
> 试试：new COS({ KeepAlive: false });

KeepAlive | 多个请求同用 TCP 连接，默认 true，若请求并发量大建议 打开
-- | --

并发量大不是应该开启吗？
另外就是之前是能上传的，今天突然不行了，这个添加KeepAlive: false可以吗

**Comment by doujinlan** [comment]
> > 试试：new COS({ KeepAlive: false });
> 
> KeepAlive	多个请求同用 TCP 连接，默认 true，若请求并发量大建议 打开
> 并发量大不是应该开启吗？
> 另外就是之前是能上传的，今天突然不行了，这个添加KeepAlive: false可以吗

请求upload接口的时候，也会弹出cannot post /api/upload xhr status:500

**Comment by doujinlan** [comment]
> 试试：new COS({ KeepAlive: false });

还是不行

**Comment by livehigh** [comment]
> > 试试：new COS({ KeepAlive: false });
> 
> 还是不行

辛苦测试下最新版本是否能够复现
