### ISSUE TITLE
Duplicate identifier 'Range'.

### ISSUE THREAD

**Issue by S-mohan** [tencentyun/cos-nodejs-sdk-v5#116]
cos-nodejs-sdk-v5/index.d.ts:1156:5 - error TS2300: Duplicate identifier 'Range'.

**Comment by zanpen2000** [comment]
same here. 

我这报一样的错误

**Comment by livehigh** [comment]
> cos-nodejs-sdk-v5/index.d.ts:1156:5 - error TS2300: Duplicate identifier 'Range'.

v2.11.0已修复，感谢反馈

**Comment by livehigh** [comment]
fixed in v2.11.0
