### ISSUE TITLE
什么时候支持async/await，现在函数外面拿不到返回值

### ISSUE THREAD

**Issue by bigbigbigbear** [tencentyun/cos-nodejs-sdk-v5#117]
什么时候支持async/await，现在函数外面拿不到返回值

**Comment by carsonxu** [comment]
支持的不要传 callback 的时候，就是返回 Promise 实例
`await cos.putObject(opt);`

**Comment by bigbigbigbear** [comment]
> 支持的不要传 callback 的时候，就是返回 Promise 实例 `await cos.putObject(opt);`

测试可以，谢谢，这种用法可以放在demo或者文档里吗？

**Comment by livehigh** [comment]
> > 支持的不要传 callback 的时候，就是返回 Promise 实例 `await cos.putObject(opt);`
> 
> 测试可以，谢谢，这种用法可以放在demo或者文档里吗？

近期会补充在demo里的哈

**Comment by yunfan** [comment]
> > > 支持的不要传 callback 的时候，就是返回 Promise 实例 `await cos.putObject(opt);`
> > 
> > 
> > 测试可以，谢谢，这种用法可以放在demo或者文档里吗？
> 
> 近期会补充在demo里的哈

到现在也没放进文档里 本来打算去反馈的 灵机一动到这里搜了下才知道 
希望推进下吧 与人方便 也是给自己方便
