### ISSUE TITLE
typescript 项目 build的时候报错..重新安装也不行

### ISSUE THREAD

**Issue by leonxiao007** [tencentyun/cos-nodejs-sdk-v5#119]
node_modules/_cos-nodejs-sdk-v5@2.10.10@cos-nodejs-sdk-v5/index.d.ts:1156:5 - error TS2300: Duplicate identifier 'Range'.

1156     Range?: Range;

**Comment by leonxiao007** [comment]
index.d.ts

**Comment by leonxiao007** [comment]
1156     Range?: Range;
1186     Range?: string;
index.d.ts 文件里的第1156 和1186行重复了属性名..

**Comment by livehigh** [comment]
v2.11.0已修复，感谢反馈

> 1156 Range?: Range; 1186 Range?: string; index.d.ts 文件里的第1156 和1186行重复了属性名..
