### ISSUE TITLE
util.js问题

### ISSUE THREAD

**Issue by juzhuo** [tencentyun/cos-nodejs-sdk-v5#125]
![image](https://user-images.githubusercontent.com/50069099/145761425-29f4a96c-ac6a-4ced-9dd1-33eca977e629.png)
这段代码可能会引起错误
![image](https://user-images.githubusercontent.com/50069099/145761468-6e8ac6cf-7aa6-4025-b53f-b3569db877b0.png)

**Comment by livehigh** [comment]
没有运行在nodejs环境？

**Comment by juzhuo** [comment]
是nodejs环境

**Comment by livehigh** [comment]
> 是nodejs环境
具体是啥环境。能否在这段源码前打印下global
