### ISSUE TITLE
"cos-nodejs-sdk-v5": "^2.9.20", 上传文件失败但是返回 200

### ISSUE THREAD

**Issue by chf007** [tencentyun/cos-nodejs-sdk-v5#127]
流水线工作目录该文件是有生成的且有内容
![wecom-temp-35f2200307b896eb094902f4d8c56cff](https://user-images.githubusercontent.com/358650/147811705-cc278e55-6763-4ad6-aebb-679f7d03d92f.png)

上传返回 200 状态码，但实际上没上传成功
![wecom-temp-981e01a1846d236093324c70a2552c9f](https://user-images.githubusercontent.com/358650/147811709-44b35f29-ad3c-447c-af33-6891d435d98c.png)

上传代码如下
![image](https://user-images.githubusercontent.com/358650/147811837-c023dc7b-84ed-401d-ba71-7c9c72f26542.png)

COS 里是 0B
![wecom-temp-f3fcaa26b56b0fb0be6f4140bd939f20](https://user-images.githubusercontent.com/358650/147811764-1b27616c-6221-46ab-9827-b491010cdf47.png)

cos-nodejs-sdk-v5 版本 ^2.9.20 ，看看是不是已知问题，升到最新版就能解决。但是看返回的错误码貌似问题不在 SDK，而在服务端。

**Comment by livehigh** [comment]
辛苦上传时加ContentLength参数再试下
https://cloud.tencent.com/document/product/436/64980#.E7.AE.80.E5.8D.95.E4.B8.8A.E4.BC.A0.E5.AF.B9.E8.B1.A1
Body: fs.createReadStream(filePath), // 上传文件对象
ContentLength: fs.statSync(filePath).size,
