### ISSUE TITLE
关于 UseAccelerate 选项

### ISSUE THREAD

**Issue by timqian** [tencentyun/cos-nodejs-sdk-v5#132]
目前只在代码里看到了这个选项，找不到相关文档的介绍。想问一下这个功能可用吗？什么时候会发布？

Ref: 
- https://github.com/tencentyun/cos-nodejs-sdk-v5/blob/master/sdk/cos.js#L42 
- https://cloud.tencent.com/document/product/436/8629

**Comment by carsonxu** [comment]
可以用。文档近期更新。

**Comment by timqian** [comment]
@carsonxu 文档有更新了希望可以在这里提醒一下

**Comment by livehigh** [comment]
> @carsonxu 文档有更新了希望可以在这里提醒一下

文档已更新
https://cloud.tencent.com/document/product/436/8629#.E9.85.8D.E7.BD.AE.E9.A1.B9
https://cloud.tencent.com/document/product/436/55438#.E5.85.A8.E7.90.83.E5.8A.A0.E9.80.9F.E5.9F.9F.E5.90.8D
