### ISSUE TITLE
有没有计划支持 【变更文件存储类型】

### ISSUE THREAD

**Issue by lxfriday** [tencentyun/cos-nodejs-sdk-v5#146]
目前官网文档没有找到变更文件存储类型的sdk接口

**Comment by livehigh** [comment]
可参考文档
https://cloud.tencent.com/document/product/436/64984#.E4.BF.AE.E6.94.B9.E5.AF.B9.E8.B1.A1.E5.AD.98.E5.82.A8.E7.B1.BB.E5.9E.8B
