### ISSUE TITLE
error TS2430: Interface 'RequestParams' incorrectly extends interface 'BucketParams'.

### ISSUE THREAD

**Issue by kushao** [tencentyun/cos-nodejs-sdk-v5#155]
cos-nodejs-sdk-v5@2.11.14

node_modules/cos-nodejs-sdk-v5/index.d.ts:1867:13 - error TS2430: Interface 'RequestParams' incorrectly extends interface 'BucketParams'.
  Property 'Bucket' is optional in type 'RequestParams' but required in type 'BucketParams'.

1867   interface RequestParams extends BucketParams {
                 ~~~~~~~~~~~~~

**Comment by livehigh** [comment]
fixed in v2.11.15
感谢反馈~
