### ISSUE TITLE
SDK's ts checked error

### ISSUE THREAD

**Issue by Huaxink** [tencentyun/cos-nodejs-sdk-v5#156]
error TS2430: Interface 'RequestParams' incorrectly extends interface 'BucketParams'.
Property 'Bucket' is optional in type 'RequestParams' but required in type 'BucketParams'.
![微信图片_20221102104134](https://user-images.githubusercontent.com/22829048/199384061-7ca73fa6-b627-4ed7-a6ef-84527ea602ab.jpg)

**Comment by livehigh** [comment]
fixed in v2.11.15
感谢反馈~
