### ISSUE TITLE
上传文件显示missing param SecretId的错误

### ISSUE THREAD

**Issue by coderjy** [tencentyun/cos-nodejs-sdk-v5#161]
问题：SecretId是传了的，但还是提示missing param SecretId
解决：在cos.js文件中修改89行代码Credentials的判断条件

源代码：
   ` if (this.options.Credentials) {`
      `  this.options.SecretId = this.options.Credentials.secretId || '';`
       ` this.options.SecretKey = this.options.Credentials.secretKey || '';`
    

修改后的代码： this.options.Credentials是一个对象，if中是永远成立的，就需要对secretId,secretKey进行单独判断
 `if (this.options.Credentials.secretId && this.options.Credentials.secretKey) {`
      `  this.options.SecretId = this.options.Credentials.secretId || '';`
     `   this.options.SecretKey = this.options.Credentials.secretKey || '';`
`    }`

**Comment by livehigh** [comment]
辛苦更新到最新版2.11.18  这里已经修复 感谢反馈~
