### ISSUE TITLE
我在使用分片上传2GB的zip文件到时候发生数据丢失问题

### ISSUE THREAD

**Issue by WumaCoder** [tencentyun/cos-nodejs-sdk-v5#164]
我在使用分片上传2GB的zip文件到时候发生数据丢失问题。
现象：

上传之后，下载下来解压失败
上传之后，下载下来文件大小小于源文件

**Comment by livehigh** [comment]
请检查下上传时的文件大小是否完整

**Comment by WumaCoder** [comment]
> 请检查下上传时的文件大小是否完整

我使用的是sdk上传的，怎么获取文件大小是否完整呢

**Comment by livehigh** [comment]
> > 请检查下上传时的文件大小是否完整
> 
> 我使用的是sdk上传的，怎么获取文件大小是否完整呢

比如上传时打印下文件大小呢 对比本地大小是否一致。

**Comment by WumaCoder** [comment]
已经解决
