### ISSUE TITLE
2.10.10版本出现ts错误，重复定义Range字段

### ISSUE THREAD

**Issue by 1801256646** [tencentyun/cos-nodejs-sdk-v5#166]
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/85598171/224882929-ceb957e2-cc0b-47da-a46b-b987a95f86c4.png">
index.d.ts文件中，望尽快修复

**Comment by livehigh** [comment]
辛苦更新下版本哈 之前的版本里已经修复了~
