### ISSUE TITLE
怎么对文件夹进行操作

### ISSUE THREAD

**Issue by foreshadow** [tencentyun/cos-nodejs-sdk-v5#17]
好像getBucket没有列出文件夹信息，我也没找到对文件夹操作的方法。

**Comment by htfy96** [comment]
似乎根据文档是v5 API中没有文件夹操作了？求证实

**Comment by carsonxu** [comment]
对象存储本身没有文件夹的概念，你可以putObject创建一个 / 结尾的空 Object 用来代表文件夹。
