### ISSUE TITLE
`COS.downloadFile` 的响应定义不准确

### ISSUE THREAD

**Issue by billychannnnnn** [tencentyun/cos-nodejs-sdk-v5#175]
https://github.com/tencentyun/cos-nodejs-sdk-v5/blob/42a01d0ea7a5c43e987f79b6efa6eea4a3dd27aa/index.d.ts#L2330

https://github.com/tencentyun/cos-nodejs-sdk-v5/blob/42a01d0ea7a5c43e987f79b6efa6eea4a3dd27aa/index.d.ts#L1210

对于`downloadFile`方法，返回的`Body`属性并不是`Buffer`而是`undefined`，估计是做了`disk storage`就不做`memory storage`了。

建议单独定义响应，如：

``` typescript
  /** downloadFile 接口返回值 */
  interface DownloadFileResult extends GeneralResult {
    /** 对象的实体标签（Entity Tag），是对象被创建时标识对象内容的信息标签，可用于检查对象的内容是否发生变化，例如"8e0b617ca298a564c3331da28dcb50df"。此头部并不一定返回对象的 MD5 值，而是根据对象上传和加密方式而有所不同 */
    ETag: ETag,
    /** 对象的版本 ID */
    VersionId?: string,
  }
```

具体源码没花时间看，但是[官方文档](https://cloud.tencent.com/document/product/436/64981#.E5.88.86.E5.9D.97.E4.B8.8B.E8.BD.BD.E5.AF.B9.E8.B1.A1)中的响应也的确没有`Body`，如果误判请原谅😁

**Comment by livehigh** [comment]
fixed in v2.12.2
