### ISSUE TITLE
请问如何上传文件到bucket下的指定目录？

### ISSUE THREAD

**Issue by Pro-YY** [tencentyun/cos-nodejs-sdk-v5#18]
请问如何上传文件到bucket下的指定目录？
 uploadslicefile 接口中的 KEY值不能有'/'，请问如何上传到指定目录呢
如 ’mybucket/mysubfolder/‘下

**Comment by carsonxu** [comment]
Key: 'mybucket/mysubfolder/a.jpg'

**Comment by Pro-YY** [comment]
谢谢！
建议文档中简单提一下，我之前面错加了'/'，所以失败了。
腾讯云加油！
