### ISSUE TITLE
大文件下载会超出Buffer的最大值（RangeError: Invalid typed array length）

### ISSUE THREAD

**Issue by 0neSe7en** [tencentyun/cos-nodejs-sdk-v5#19]
原因是在使用request的时候传了回调函数。然后会调用[request.readResponseBody](https://github.com/request/request/blob/master/request.js#L1135)方法。

在创建request对象的时候会判断是否传递了回调函数，如果传递了则：https://github.com/request/request/blob/master/request.js#L1092

**Comment by carsonxu** [comment]
v2.0.8 已修复这个问题
