### ISSUE TITLE
getBucket方法的data类型有些问题

### ISSUE THREAD

**Issue by Peng1203** [tencentyun/cos-nodejs-sdk-v5#191]
index.d.ts中 getBucket cb 函数的data 类型标注的是 COS.GetBucketResult 但是 COS.GetBucketResult类型上 没有 Prefix 属性
![image](https://github.com/tencentyun/cos-nodejs-sdk-v5/assets/79517958/0f41519f-e437-4261-8c9e-da42ab51f624)
![image](https://github.com/tencentyun/cos-nodejs-sdk-v5/assets/79517958/c296fc9f-e281-49ae-88cf-aa9e5d499249)

版本 2.12.4

**Comment by livehigh** [comment]
感谢反馈 我们下个版本将修复这里的类型
