### ISSUE TITLE
TypeError: Property 'StartTime' is required in type 'Credentials'.

### ISSUE THREAD

**Issue by liyunsheng** [tencentyun/cos-nodejs-sdk-v5#194]
SDK用临时密钥初始化时，在callback中参数要求必现传入`StartTime`，但是官方文档 [Node.js SDK > 快速入门](https://cloud.tencent.com/document/product/436/8629#.E9.85.8D.E7.BD.AE.E9.A1.B9) 中`StartTime`是非必填的（如下图），希望类型声明可以对其文档。

```javascript
new COS({
  getAuthorization(options, callback) {
    callback({
      TmpSecretId: '',
      TmpSecretKey: '',
      SecurityToken: '',
      ExpiredTime: 111,
    });
  },
});
```

> Property 'StartTime' is missing in type '{ TmpSecretId: string; TmpSecretKey: string; SecurityToken: string; ExpiredTime: number; }' but required in type 'Credentials'.

<img width="1023" alt="image" src="https://github.com/tencentyun/cos-nodejs-sdk-v5/assets/9405946/0c98b4ea-7111-49e1-950f-696b5c292c51">

**Comment by livehigh** [comment]
感谢反馈 我们优化下文档
