### ISSUE TITLE
大哥你升级完不测一下吗

### ISSUE THREAD

**Issue by asself** [tencentyun/cos-nodejs-sdk-v5#198]
<img width="829" alt="image" src="https://github.com/tencentyun/cos-nodejs-sdk-v5/assets/17953208/acf1b32a-dbb6-4f39-85ac-8daa4fe423e7">

<img width="389" alt="企业微信截图_9714afac-306e-4806-80b8-6c8a6e56a4c9" src="https://github.com/tencentyun/cos-nodejs-sdk-v5/assets/17953208/4a6249ee-8726-4c42-961b-de5adaa0279c">你package.json中声明只要node>=6就行了，现在升级后node12直接给跑挂了

**Comment by asself** [comment]
这个语法就直接这么用了，也不考虑node版本
<img width="646" alt="image" src="https://github.com/tencentyun/cos-nodejs-sdk-v5/assets/17953208/ff9e3547-2dc7-450d-9e2e-a09cd43294ff">

**Comment by livehigh** [comment]
辛苦升级 2.13.1 版本
