### ISSUE TITLE
非标准Error难以调试

### ISSUE THREAD

**Issue by forsaken628** [tencentyun/cos-nodejs-sdk-v5#20]
现在抛出的错误不是标准Error对象，没有堆栈，难以跟踪debug，建议使用下面的形式
var e=new Error(‘some error’)
e.info = 'other info'
throw e

**Comment by carsonxu** [comment]
谢谢建议，考虑到影响已有用户的使用，暂不修改返回值，后续大版本更新再优化。

**Comment by hlipeter** [comment]
是   ，五天前 你们又改了错误返回方式！
删除 有文件的 bucket 错误码  

![qq20170829-131954](https://user-images.githubusercontent.com/22487962/29805516-c79facaa-8cbc-11e7-932f-20ca79040f6b.png)

就这样了对吗？错误内容都没有

 能测试了再提交吗？能稳定一点吗？

**Comment by carsonxu** [comment]
"五天前 你们又改了错误返回方式！" 什么意思？返回码变了？

**Comment by LinkXSystem** [comment]
请问这个错误通常是由什么原因造成的：{ error: 'lack of required params' }
这是我写的上传代码：
```js
var cos = require('cos-nodejs-sdk-v5');

var client = new cos({
    AppId: 'xxx',
    SecretId: 'xxx',
    SecretKey: 'xxx',
    Domain: 'linksystem-1251985701.cos.ap-shanghai.myqcloud.com'
});

client.sliceUploadFile({
    Bucket: 'linksystem',
    Region: 'ap-shanghai',
    key: 'index.js',
    FilePath: __dirname + '/index.js'
}, function (err, data) {
    console.log(err, data);
});
```

**Comment by poppinlp** [comment]
+1 这里使用起来确实挺麻烦的

**Comment by carsonxu** [comment]
2.9.0 已优化
