### ISSUE TITLE
小白求问 uniapp 引入  "cos-nodejs-sdk-v5": "^2.13.5"  编译出现 TypeError: util$6.inherits is not a function

### ISSUE THREAD

**Issue by octGitHub** [tencentyun/cos-nodejs-sdk-v5#203]
以下是我这里安装和引入的情况。
只要屏蔽了   import COS from 'cos-nodejs-sdk-v5';  就不会报错了， 这个一般是什么情况？

![issuse01](https://github.com/tencentyun/cos-nodejs-sdk-v5/assets/14867254/051a0593-37bf-4935-8e77-4560ccd747d7)
![issue02](https://github.com/tencentyun/cos-nodejs-sdk-v5/assets/14867254/4685ae40-af99-4acf-91af-92998c39a938)
![issue03](https://github.com/tencentyun/cos-nodejs-sdk-v5/assets/14867254/f0ec15bb-64b6-4b98-a2de-0f8790a31cac)

**Comment by livehigh** [comment]
您好，uniapp 暂无支持的 sdk，可参考直传 demo：https://cloud.tencent.com/document/product/436/71469

**Comment by octGitHub** [comment]
> 您好，uniapp 暂无支持的 sdk，可参考直传 demo：https://cloud.tencent.com/document/product/436/71469

好的，谢谢，我试试
