### ISSUE TITLE
按官方demo执行报错

### ISSUE THREAD

**Issue by wyrjob** [tencentyun/cos-nodejs-sdk-v5#207]
环境
- node v20.13.1
- tsc 5.4.5
- ts-node v10.9.2

安装
```
npm install cos-nodejs-sdk-v5
```

执行
```
const cos = new COS({
    SecretId: process.env.CLOUD_SECRET_ID,
    SecretKey: process.env.CLOUD_SECRET_KEY,
});
```
报错
TypeError: cos_nodejs_sdk_v5_1.default is not a constructor

**Comment by livehigh** [comment]
什么环境？
如何引用的 sdk，辛苦再提供完整代码。

**Comment by wyrjob** [comment]
> 什么环境？ 如何引用的 sdk，辛苦再提供完整代码。

是```import COS from 'cos-nodejs-sdk-v5'```导致的
换成```const COS = require('cos-nodejs-sdk-v5')```就好了

这SDK对typescript的语法 不是很支持吗？

**Comment by wyrjob** [comment]
在tsconfig.json中添加```"esModuleInterop": true```也能解决

**Comment by livehigh** [comment]
> 用`import COS from 'cos-nodejs-sdk-v5'`写法的话 在tsconfig.json中添加`"esModuleInterop": true`也能用

可以的。使用后缀名也可以区分比如
 index.cjs
const COS = require('cos-nodejs-sdk-v5');

index.mjs
import COS from 'cos-nodejs-sdk-v5';
