### ISSUE TITLE
getService方法  返回的Bucket时间格式有误

### ISSUE THREAD

**Issue by hlipeter** [tencentyun/cos-nodejs-sdk-v5#21]
随便创建一个Bucket    接口返回的时间是：   2017-08-11T09:26:52Z

UTC时间格式？

解析一下时间  

结果是：   2017-08-11 17:26:52

昨天下午创建的bucket    拿到的时间转换一下后是  凌晨的...

你们的Bucket时间拿错了   真的

Object 返回的时间是正确的！

**Comment by carsonxu** [comment]
谢谢反馈，这个是后端 api 返回的时间，已反馈给开发。

**Comment by carsonxu** [comment]
这个时间错误问题已修复
