### ISSUE TITLE
能否支持一下typescript

### ISSUE THREAD

**Issue by ayuanlmo** [tencentyun/cos-nodejs-sdk-v5#216]
用ts编写时候`cos-nodejs-sdk-v5`总是缺少类型定义。如果断言成`any`将毫无意义。希望增加`@types/cos-nodejs-sdk-v5`。如果还能支持 `ES Module`，那将特别棒。

**Comment by livehigh** [comment]
感谢反馈，目前以 index.d.ts 的形式补偿类型定义。考虑增加@types/cos-nodejs-sdk-v5～

**Comment by ayuanlmo** [comment]
好的，感谢
