### ISSUE TITLE
sliceUploadFile 方法上传文件以后，静态网站不能访问

### ISSUE THREAD

**Issue by sdlzhd** [tencentyun/cos-nodejs-sdk-v5#24]
代码如下：
```javascript
uploadFileList.forEach((item)=>{
    cos.sliceUploadFile({
        Bucket: args.bucket,
        Region: args.region,
        Key: item.key,
        FilePath: item.filePath,
    }, (err, data)=>{
        if (err) {
            console.log(err);
        } else {
            console.log(data);
        }
    });
 });
```
其中，uploadFileList是一个数组，遍历出的item对象如下
```javascript
{ 
    key: '/tags/PHP/index.html',
    filePath: '/home/dongdong/Documents/hexo/public/tags/PHP/index.html'
 }
```
假设静态托管的网址为http://exp.com
上传完成后，访问这个页面（http://exp.com/tags/PHP），会报unexpectedly closed the connection.
但是如果访问http://exp.com/tags/PHP/index.html，就正常，而且我如果手动上传这个文件，就不会出现这种情况，所有的访问都是正常的

**Comment by sdlzhd** [comment]
我把上传方法替换成putObject之后，就可以正常使用了

**Comment by carsonxu** [comment]
ok，不知道你这里是不是权限问题？putObject 是不分片的上传，如果能满足也可以。

**Comment by sdlzhd** [comment]
我觉得不是权限问题，我并没有动过权限，而且我打开看文件的详细信息，也很明确的告诉我继承自Bucket，没有找到原因，就先用putObject吧。

还有一个事情，本来我是想用bluebird把cos转换成Promise的，结果一直告诉我this._task(大概是这样，具体是哪个忘记了) not a function，我大概看了看源代码就放弃了。

是否有打算，把Nodejs的这些回调函数转换成Promise的方式呢？

Sent from Mail for Windows 10

**Comment by carsonxu** [comment]
Promise 可能不支持，我们后续先看看不支持 bluebird 是什么原因，感谢关注。

**Comment by sdlzhd** [comment]
好的。

Sent from Mail for Windows 10
