### ISSUE TITLE
希望改写支持Promise

### ISSUE THREAD

**Issue by a632079** [tencentyun/cos-nodejs-sdk-v5#27]
支持Promise 能够回避一些难以调试的错误，同时也能减轻代码横向发展的症状。十分期待，未来对此的支持

**Comment by carsonxu** [comment]
谢谢反馈，之前有考虑过支持 Promise 格式，但优先级不高，暂未支持，我们后续再评估下。

**Comment by ypli0629** [comment]
@carsonxu 还没评估好？

**Comment by poppinlp** [comment]
@carsonxu 
Hi. 不知道这边评估的如何了呢？因为最近在项目中有使用到，所以也会有所期望。
如果你们评估觉得 OK 的话，愿意一起讨论方案和后续实现，如果需要帮忙的话。:)

**Comment by firede** [comment]
没有官方的 `Promise` 的支持是挺麻烦的，自己改造吧：

```js
const { promisify } = require("util")

// 你的 COS 实例
const cos = new COS({ /* ... */ })

// 将 promisify 后的方法挂到实例上
cos.pHeadBucket = promisify(cos.headBucket)

// Promise 风格示例
cos.pHeadBucket(params)
  .then(res => console.log(res))
  .catch(err => console.error(err))

// async/await 风格示例
async function yourAsyncFn() {
  const res = await cos.pHeadBucket(params)
  console.log(res)
}
yourAsyncFn().catch(err => console.log(err))
```

@carsonxu 感觉这问题挺常见，要不加到文档里？

**Comment by carsonxu** [comment]
近期支持 promise

**Comment by QJvic** [comment]
> 没有官方的 `Promise` 的支持是挺麻烦的，自己改造吧：
> 
> ```js
> const { promisify } = require("util")
> 
> // 你的 COS 实例
> const cos = new COS({ /* ... */ })
> 
> // 将 promisify 后的方法挂到实例上
> cos.pHeadBucket = promisify(cos.headBucket)
> 
> // Promise 风格示例
> cos.pHeadBucket(params)
>   .then(res => console.log(res))
>   .catch(err => console.error(err))
> 
> // async/await 风格示例
> async function yourAsyncFn() {
>   const res = await cos.pHeadBucket(params)
>   console.log(res)
> }
> yourAsyncFn().catch(err => console.log(err))
> ```
> 
> @carsonxu 感觉这问题挺常见，要不加到文档里？

cos.pPutObject = promisify(cos.putObject);
cos.pDeleteObject == promisify(cos.deleteObject);
console.log(cos.pPutObject);  //这里输出function
console.log(cos.pDeleteObject); //这里输出undefined
用这种方法，putObject可以，而deleteObject却不行。可以请教一下为什么吗？

**Comment by QJvic** [comment]
> > 没有官方的 `Promise` 的支持是挺麻烦的，自己改造吧：
> > ```js
> > const { promisify } = require("util")
> > 
> > // 你的 COS 实例
> > const cos = new COS({ /* ... */ })
> > 
> > // 将 promisify 后的方法挂到实例上
> > cos.pHeadBucket = promisify(cos.headBucket)
> > 
> > // Promise 风格示例
> > cos.pHeadBucket(params)
> >   .then(res => console.log(res))
> >   .catch(err => console.error(err))
> > 
> > // async/await 风格示例
> > async function yourAsyncFn() {
> >   const res = await cos.pHeadBucket(params)
> >   console.log(res)
> > }
> > yourAsyncFn().catch(err => console.log(err))
> > ```
> > 
> > 
> > @carsonxu 感觉这问题挺常见，要不加到文档里？
> 
> cos.pPutObject = promisify(cos.putObject);
> cos.pDeleteObject == promisify(cos.deleteObject);
> console.log(cos.pPutObject); //这里输出function
> console.log(cos.pDeleteObject); //这里输出undefined
> 用这种方法，putObject可以，而deleteObject却不行。可以请教一下为什么吗？

自己二了，开了eslint后发现写的是==。   。。。。。

**Comment by Xinayu** [comment]
这个问题挺常见的，使用util的promisify 对api进行改造即可。
阿里和腾讯都不支持promise，七牛云就可以....

**Comment by swy1996** [comment]
包裹一层promise就好了 我的解决方案
``` 
let data = await new Promise((res, rej) => {
	cos.putObject({},
	function(err, data) {
		if(err) {
			rej(err)
		} else {
			res(data)
		}
	})
})
```

**Comment by Azero-NG** [comment]
同需要支持promise

**Comment by greenhat616** [comment]
@Xinayu 补充一下，貌似阿里云的支持了。我使用阿里云邮件推送（Aliyun DirectMail）的官方SDK，已经支持 Promise，UPYUN 也支持了。目前就腾讯这儿还不支持：（

**Comment by xsephiroth** [comment]
写个builder

```javascript
const cosPromise = fn => params => new Promise((resolve, reject) => {
  fn(params, (err, data) =>
    err ? reject(err) : resolve(data)
  )
})

const cosGetObject = cosPromise(cos.getObject.bind(cos));
const cosPutObject = cosPromise(cos.putObject.bind(cos));
const cosDeleteObject = cosPromise(cos.deleteObject.bind(cos));
```

**Comment by carsonxu** [comment]
已支持 Promise 和 await 调用 v2.8.0

**Comment by Erchoc** [comment]
> 已支持 Promise 和 await 调用 v2.8.0

大兄弟，为啥 2.9.1 又无法使用 await 了呢?

**Comment by carsonxu** [comment]
支持的，你是不是传入了callback？

**Comment by Erchoc** [comment]
> 支持的，你是不是传入了callback？

![image](https://user-images.githubusercontent.com/19908809/105845508-d049a880-6015-11eb-92b5-d608c1e7dc5b.png)

这叫支持了？我记得几周前的版本是正常的

**Comment by carsonxu** [comment]
```
// test Promsise
cos.headBucket({
    Bucket: config.Bucket,
    Region: config.Region
}).then(data => {
    console.log('Promise:', data);
});

// test await
async function test() {
    const data = await cos.headBucket({
        Bucket: config.Bucket,
        Region: config.Region
    });
    console.log('await:', data);
}
test();
```
@Erchoc 这两个都可用，是遇到什么问题导致调用失败？
