### ISSUE TITLE
问题？求解

### ISSUE THREAD

**Issue by Cbinbin** [tencentyun/cos-nodejs-sdk-v5#3]
1、COS.config.setAppInfo(AppId, SecretId, SecretKey, timeout)
v3 nodeSDK之前有上面这接口，这里可不可以用？我用时报错 "....setAppInfo ##undefined"

2、在bucket里面建文件夹，用putObject() 可以上传到bucket的子文件夹里面吗？

3、putObject()返回的ETag是做什么用的？有包含文件信息？MD5 算法校验值可以解密？上传的是图片或视频可以通过指定的 url 预览吗？
以上问题求解啊，谢谢！

**Comment by meteormatt** [comment]
2、在bucket里面建文件夹，用putObject() 可以上传到bucket的子文件夹里面吗？
可以的

3、putObject()返回的ETag是做什么用的？有包含文件信息？MD5 算法校验值可以解密？上传的是图片或视频可以通过指定的 url 预览吗？
https://www.qcloud.com/document/product/436/8287
> ETag 	返回文件的 SHA-1 算法校验值。ETag 的值可以用于检查 Object 的内容是否发生变化。
应该可以预览的。

**Comment by Cbinbin** [comment]
谢谢，我大概知道怎么用了

**Comment by Cbinbin** [comment]
配置：
...
var cos = new COS({...})
...
更新得漂亮！！！
