### ISSUE TITLE
关于上传进度

### ISSUE THREAD

**Issue by a631807682** [tencentyun/cos-nodejs-sdk-v5#31]
我有一个疑问，我看demo都是从浏览器端上传完整文件到服务器，再从服务器上传到qcloud，这种方式我应该如何控制进度，是否存在代理的方式，之间把上传流转到qcloud而不再本地存储。

**Comment by carsonxu** [comment]
这种方式的进度只能是前端到你自己服务器的进度。
为何不用 cos-js-sdk-v5 直接上传到 cos 呢？

**Comment by a631807682** [comment]
是的，我看cos-js-sdk-v5的demo关于上传的好像是putObject和sliceUploadFile方法，好像都是读取本地文件上传到cos的吧，而本地文件不是已经在服务器了吗。

**Comment by carsonxu** [comment]
“而本地文件不是已经在服务器了吗”，什么意思？

**Comment by a631807682** [comment]
cos-js-sdk-v5不是nodejs的一个包吗，我在nodejs所运行的服务器上设置FilePath执行cos.sliceUploadFile上传到cos，那么这个文件不是需要已经在我nodejs所在的服务器上了吗。

**Comment by carsonxu** [comment]
当前 issue 所在的是 nodejs 的版本，cos-js-sdk-v5 是浏览器的版本

**Comment by a631807682** [comment]
噢，不好意思我看错了，我去看看，谢谢。
