### ISSUE TITLE
请问为什么一直报403错误

### ISSUE THREAD

**Issue by meibin08** [tencentyun/cos-nodejs-sdk-v5#38]
使用该sdk ,sliceUploadFile 上传图片 ，一直报403错误，求解，东西都没有错

{"error":{"Code":"AccessDenied","Message":"Access Denied.","Resource":"z**p-1251**43.cos.ap-sh**ai.myqcloud.com/upload/1526661248697.png","RequestId":"NWFmZjAwNzlfZGFhMDY4NjRfODZkNl83N2I3YQ==","TraceId":"OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjZmJjODk2ZGRhYzY5ODkwOWQ1NThkZTFhOWQyNTY3MjM="},"statusCode":403,"headers":{"content-type":"application/xml","content-length":"476","connection":"close","date":"Fri, 18 May 2018 16:34:01 GMT","server":"tencent-cos","x-cos-request-id":"NWFmZjAwNzlfZGFhMDY4NjRfODZkNl83N2I3YQ==","x-cos-trace-id":"OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjZmJjODk2ZGRhYzY5ODkwOWQ1NThkZTFhOWQyNTY3MjM="}

**Comment by carsonxu** [comment]
这里解决了吗？是否使用了临时密钥，然后没回传 XCOSSecurityToken 给 SDK？

**Comment by meibin08** [comment]
已经解决了，谢谢 @carsonxu

**Comment by JerryJavaCoding** [comment]
> 使用该sdk ,sliceUploadFile 上传图片 ，一直报403错误，求解，东西都没有错
> 
> {"error":{"Code":"AccessDenied","Message":"Access Denied.","Resource":"z**p-1251**43.cos.ap-sh**ai.myqcloud.com/upload/1526661248697.png","RequestId":"NWFmZjAwNzlfZGFhMDY4NjRfODZkNl83N2I3YQ==","TraceId":"OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjZmJjODk2ZGRhYzY5ODkwOWQ1NThkZTFhOWQyNTY3MjM="},"statusCode":403,"headers":{"content-type":"application/xml","content-length":"476","connection":"close","date":"Fri, 18 May 2018 16:34:01 GMT","server":"tencent-cos","x-cos-request-id":"NWFmZjAwNzlfZGFhMDY4NjRfODZkNl83N2I3YQ==","x-cos-trace-id":"OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjZmJjODk2ZGRhYzY5ODkwOWQ1NThkZTFhOWQyNTY3MjM="}

也遇到这个问题，请问您当时是怎么解决的

**Comment by meibin08** [comment]
你好，当时好像是因为主账号给当前分配的的子账户对应的存储目录，没有开启读写权限，所以不能存入


原始邮件
发件人:jerry1994notifications@github.com
收件人:tencentyun/cos-nodejs-sdk-v5cos-nodejs-sdk-v5@noreply.github.com
抄送:South·Sumeibin08@163.com; Authorauthor@noreply.github.com
发送时间:2018年9月25日(周二) 20:10
主题:Re: [tencentyun/cos-nodejs-sdk-v5] 请问为什么一直报403错误 (#38)


使用该sdk ,sliceUploadFile 上传图片 ，一直报403错误，求解，东西都没有错
{"error":{"Code":"AccessDenied","Message":"Access Denied.","Resource":"zp-125143.cos.ap-sh**ai.myqcloud.com/upload/1526661248697.png","RequestId":"NWFmZjAwNzlfZGFhMDY4NjRfODZkNl83N2I3YQ==","TraceId":"OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjZmJjODk2ZGRhYzY5ODkwOWQ1NThkZTFhOWQyNTY3MjM="},"statusCode":403,"headers":{"content-type":"application/xml","content-length":"476","connection":"close","date":"Fri, 18 May 2018 16:34:01 GMT","server":"tencent-cos","x-cos-request-id":"NWFmZjAwNzlfZGFhMDY4NjRfODZkNl83N2I3YQ==","x-cos-trace-id":"OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjZmJjODk2ZGRhYzY5ODkwOWQ1NThkZTFhOWQyNTY3MjM="}
也遇到这个问题，请问您当时是怎么解决的
