### ISSUE TITLE
分片上传sliceUploadFile时报错

### ISSUE THREAD

**Issue by freedomcly** [tencentyun/cos-nodejs-sdk-v5#42]
Cannot read property 'FilePath' of undefined

在cos-nodejs-sdk-v5/sdk/utils.js文件里的util.getFileUUID方法

**Comment by WumaCoder** [comment]
我在使用分片上传2GB的zip文件到时候发生数据丢失问题。
现象：
- 上传之后，下载下来解压失败
- 上传之后，下载下来文件大小小于源文件
