### ISSUE TITLE
使用putBucket时，设置权限无效问题

### ISSUE THREAD

**Issue by RuiZhuo** [tencentyun/cos-nodejs-sdk-v5#43]
ACL参数设置为'public-read'， 然后无效，在控制台中还是显示私有读写。。。

**Comment by carsonxu** [comment]
这里是因为 COS 有 v4、v5，你看到的控制台应该是 v4 控制台。
当前 sdk 只对 v5 接口生效。

**Comment by RuiZhuo** [comment]
好的
