### ISSUE TITLE
上传对象强制要求content-length，不应该

### ISSUE THREAD

**Issue by WizTeam** [tencentyun/cos-nodejs-sdk-v5#47]
当我上传一个stream的时候，并不能知道这个stream的大小。

**Comment by carsonxu** [comment]
cos.putObject 接口流式上传时，暂时需要指定 content-length header，
当前API版本已修改支持不指定 content-length，本周内会全量发布。

**Comment by holajiawei** [comment]
@carsonxu 请问现在版本发布了吗？

**Comment by shiny** [comment]
写代码写到天亮，就是为了折腾腾讯的 API，设计得太糟糕了。

**Comment by ypli0629** [comment]
+1

**Comment by poppinlp** [comment]
+1

**Comment by carsonxu** [comment]
@holajiawei 特性暂未全量发布，有需要可以提工单给 bucket 开白名单

**Comment by poppinlp** [comment]
@carsonxu 感谢回复。看起来主要是你一人在维护这个 repo？辛苦了。 :)

**Comment by carsonxu** [comment]
已支持流式上传
