### ISSUE TITLE
建议增加下载为stream的功能

### ISSUE THREAD

**Issue by WizTeam** [tencentyun/cos-nodejs-sdk-v5#48]
现在是直接保存成文件，并且是下载完成后才会回调。

应该增加下载对象为stream，这样方便把这个stream pipe到http response里面。否则的话，就只能下载到本地临时文件，然后再返回给客户。对于大文件，很容易超时，至少效率有问题。直接返回一个stream就好多了。s3，oss都是可以的

**Comment by carsonxu** [comment]
下载支持 stream 的：
```
getObject({
    ....,
    Output: fs.createWriteStream('./a.zip');
});
```

**Comment by WizTeam** [comment]
这个不行的，只是支持传递一个stream进去。我们更希望的是这个方法返回一个stream。举个例子：

当用户请求下载一个对象的时候，按照当前的方式，我需要创建一个临时文件，然后生成一个writeable stream并传递给cos，在cos下载完成前，我没办法把这个stream返回给客户。

oss，s3的做法是，我请求api，直接给我返回一个readable stream（这时候对象可能还没有开始下载，至少没有下载完成）。然后我可以直接把这个stream作为koa的body返回给客户，用户就可以下载了。

**Comment by carsonxu** [comment]
s3 是什么格式？

**Comment by WizTeam** [comment]
S3的使用方法：
```
      let params = {
        Bucket: self.bucket,
        Key: name,
      };
      //
      let req = self.client.getObject(params);
      let stream = req.createReadStream();
```
注意stream是返回值，而不是我自己创建的filestream。这样我可以直接把这个stream作为koa的body返回。

**Comment by dimkua** [comment]
同求，可以pipe给response

**Comment by borie88** [comment]
+1

**Comment by carsonxu** [comment]
近期补充支持

**Comment by duanyuanping** [comment]
请问这个功能现在支持了吗

**Comment by carsonxu** [comment]
已支持 cos.getObjectStream(opt).pipe(writeStream)
