### ISSUE TITLE
getObjectUrl返回的url无法下载

### ISSUE THREAD

**Issue by WizTeam** [tencentyun/cos-nodejs-sdk-v5#49]
报403错误

**Comment by carsonxu** [comment]
x-cos-security-token 参数只支持了部分园区，本周的全量版本会支持。

**Comment by WizTeam** [comment]
https://ru-ks-test-1252315408.cos.eu-moscow.myqcloud.com/test_files/test.txt?sign=q-sign-algorithm%3Dsha1%26q-ak%3DAKID72i8ICYEMEr0vb6D9qIWWHoBKEtLfcPx%26q-sign-time%3D1532401289%3B1532461289%26q-key-time%3D1532401289%3B1532461289%26q-header-list%3D%26q-url-param-list%3D%26q-signature%3D57e37462abddd68d44facbe6d61891f40788f605?sign=q-sign-algorithm%3Dsha1%26q-ak%3DAKID72i8ICYEMEr0vb6D9qIWWHoBKEtLfcPx%26q-sign-time%3D1532401289%3B1532461289%26q-key-time%3D1532401289%3B1532461289%26q-header-list%3D%26q-url-param-list%3D%26q-signature%3D57e37462abddd68d44facbe6d61891f40788f605

**Comment by carsonxu** [comment]
x-cos-security-token 参数 已全量支持
