### ISSUE TITLE
getBucket 返回中不包含 Location

### ISSUE THREAD

**Issue by ypli0629** [tencentyun/cos-nodejs-sdk-v5#50]
返回结果中不包含创建Bucket时返回的 Location ，这不合理吧，只是把 key 返回了

**Comment by carsonxu** [comment]
你是希望返回的 Object 都带有完整的 url？

**Comment by ypli0629** [comment]
@carsonxu 不是，只需要一个字段把图片的前缀带上就好了

**Comment by ypli0629** [comment]
根据这些信息，我没办法拼接出完整的图片url

**Comment by carsonxu** [comment]
加上你传的参数里 Bucket 和 Region，就可以拼接完整 Url，这个不一定要在返回值里体现 Url
