### ISSUE TITLE
node sdk生成的Authorization在js sdk上用不了

### ISSUE THREAD

**Issue by 982991084** [tencentyun/cos-nodejs-sdk-v5#56]
node sdk
`js
const cos = new COS({ SecretId: this.config.SecretId, SecretKey: this.config.SecretKey })
const Authorization = cos.getAuth({ Method: reqData.method, key: '', Expires: 3600 })
`
js sdk
`js
var cos = new COS({
        getAuthorization: function(options, callback) {
          callback({ Authorization: res.data.Authorization })
        }
      })
cos.putObject(
        {
          Bucket: res.data.Bucket,
          Region: res.data.Region,
          Key: Key,
          Body: Body
        },
        function(err, data) {
          console.log(err, data)
          return data
        }
      )
`
![wx1 ndm c0 2 jw6cl20](https://user-images.githubusercontent.com/22464456/46007395-88848080-c0ec-11e8-8642-93e8a791d0ca.png)

**Comment by carsonxu** [comment]
这里 Key 没加到签名计算里，所以对应不上。
```
var cos = new COS({
    SecretId: this.config.SecretId,
    SecretKey: this.config.SecretKey
})
const Authorization = cos.getAuth({
    Method: reqData.method,
    Key: reqData.key,
    Expires: 3600
})
```
