### ISSUE TITLE
[Feature Request] 支持数据万象

### ISSUE THREAD

**Issue by firede** [tencentyun/cos-nodejs-sdk-v5#62]
通过 *数据万象* 的 *持久化处理接口*，附带 *处理规则 (`Pic-Operations`)* 并将图片上传至 COS。

参考文档：https://cloud.tencent.com/document/product/460/18146

### Status

*数据万象* 与 COS 提供的域名不同，API 参数保持兼容。
现在可以通过传递 `Headers["Pic-Operations"]` 参数加入处理规则，但无法更改 API 的地址。

### Feature Request

COS 和 *数据万象* 是分开的两个服务（不像别家的云，图片处理功能是属于对象存储的附属功能），导致无法通过 SDK 使用。

期望 SDK 能官方支持 *数据万象*；如果短期无法实现，希望能提供修改 API 地址的接口，间接达成使用 *数据万象* 的目的。

**Comment by carsonxu** [comment]
看了下是调用了cos4的接口，和这个sdk没关系。
sdk v4没nodejs sdk

**Comment by firede** [comment]
感谢快速相应 👍 

> 看了下是调用了cos4的接口，和这个sdk没关系。

*持久化处理接口* 没有提供 SDK，手动拼 v4 的 API 挺麻烦的。
看来复用 COS SDK 不太现实了，我还是自己处理图片吧：）
