### ISSUE TITLE
Body对象的校验在跨iframe的时候存在问题

### ISSUE THREAD

**Issue by IveChen** [tencentyun/cos-nodejs-sdk-v5#63]
在使用富文本编辑器ueditor进行开发的时候，需要使用sliceUploadFile进行上传。然后发现一个问题，因为ueditor进行上传的页面使用的是iframe的方式，所以如果使用最外层容器即top.COS进行上传的时候，虽然params.Body是属于File，但不属于top.File(即下面的global.File)，所以导致抛出params.body error。

```
var getFileSize = function (api, params, callback) {
    var size;
    if (util.isBrowser) {
        if (typeof params.Body === 'string') {
            params.Body = new global.Blob([params.Body]);
        }
        if (params.Body instanceof global.File || params.Body instanceof global.Blob) {
            size = params.Body.size;
        } else {
            callback({error: 'params body format error, Only allow File|Blob|String.'});
            return;
        }
    }
```
我只能在每个iframe都引入文件包，并且对于ueditor使用js创建的iframe 也得补上js引用。。。
所以能否换个方式来校验prams.body(比如加上校验是否含有name,size属性之类，或者有一个自定义的校验方式？)。。

**Comment by carsonxu** [comment]
你是在浏览器使用，是不是用的这个？
https://github.com/tencentyun/cos-js-sdk-v5

**Comment by IveChen** [comment]
是的

**Comment by IveChen** [comment]
原来发错了。。我去那边。。
