### ISSUE TITLE
请问cos-nodejs-sdk-v5 支持最低的node版本是多少?

### ISSUE THREAD

**Issue by Faithree** [tencentyun/cos-nodejs-sdk-v5#66]
![image](https://user-images.githubusercontent.com/21101396/49431890-67759580-f7e9-11e8-9e1c-ca165fe9f302.png)
请问有没有历史版本支持node.js 6.0的版本

**Comment by huiyifyj** [comment]
个人建议最好在 `package.json` 中添加 `engines`, 像这样之类的:
```json
"engines": {
    "node": ">=1",
    "npm": ">=4.0",
    "yarn": ">=1.0"
}
```
