### ISSUE TITLE
文件上传还有太多要改进的地方，求跟进!!!

### ISSUE THREAD

**Issue by hlipeter** [tencentyun/cos-nodejs-sdk-v5#7]
到目前为止，上传这块儿还欠缺好多要改进的地方额。你现在只是在文件上传成功后 返回一个状态！
具体说下问题：
1、上传的过程中读取不到单个文件上传进度；
2、多文件同时上传可有什么限制？最多同时上传文件个数，以及每个文件上传的进度；
3、Upload Part［支持的块的数量为1到10000，块的大小为1 MB 到5 GB］,这里指的是所有文件加一起的块限制吧？ 那我同时上传一万多个文件怎么办！
4、暂停上传单个文件呢？暂停所有文件呢？
5、客户端异常退出或者网络断开   再到恢复   之前未上传和正在上传等的进度信息如何获取？

There's still a lot to change ！ 頑張って！

**Comment by carsonxu** [comment]
1、上传的过程中读取不到单个文件上传进度；
文件上传进度是通过回调来返回的，原本是上传完一个分片才有一次回调，昨天更新了一个版本，支持大约100ms一次回调。
[demo.js#L342-L347](https://github.com/tencentyun/cos-nodejs-sdk-v5/blob/master/demo/demo.js#L342-L347)

2. 多文件同时上传有什么限制：
  a. sliceUploadFile 方法可以传SliceSize控制每片大小，可以传 AsyncLimit 控制单文件里的分片的并发量
  b. 同时上传多个文件，暂时还未限制文件的并发（多文件并发限制后续会完善）。
  c. 每个文件上传的进度同样是通过每次传入的 onProgress 回调告知调用者。

3. ［支持的块的数量为1到10000，块的大小为1 MB 到5 GB］
这里指的是服务器的限制。

4. 暂停上传
这里指的是取消上传？还是真的暂停，还想重新开始的？
后续会先补上取消，暂停和重新开始也会找时间补上。

5. 异常退出
文件上传一部分分片之后，重新发起同一个文件，同一个路径的上传，会从服务器拉已上传 list，再开始上传未完成的块。
不过这部分还可以优化空间。

谢谢提了诸多改进建议！

**Comment by carsonxu** [comment]
暂停上传，取消上传已支持。
https://github.com/tencentyun/cos-nodejs-sdk-v5/blob/master/demo/demo.js#L451-L473

**Comment by hlipeter** [comment]
@carsonxu 上个版本真解决了大文件下载报错的问题，不错哦！

另外，下载文件   什么时候能支持暂停和断点续传吖？  好期待

**Comment by carsonxu** [comment]
感谢关注，下载的暂停支持，短期内没考虑实现

**Comment by lockiechen** [comment]
批量上传文件时，单个文件出错时，回调函数内的err不会被赋值，我应该在哪里终止上传流程，或者有办法可以回退本次已上传的文件么
