### ISSUE TITLE
分片上传进度不准确的问题

### ISSUE THREAD

**Issue by lyswhut** [tencentyun/cos-nodejs-sdk-v5#71]
我使用`cos.sliceUploadFile`对文件进行上传，发现大文件的上传进度不准确，估计是被分片了的原因，以下是上传时打出的log：
![20190718183953](https://user-images.githubusercontent.com/20365169/61451200-7df0eb80-a98b-11e9-80ca-3c7ef7147a3d.png)
可以看到`loaded`与`percent`不对，请问这是什么原因？

**Comment by carsonxu** [comment]
```
if (this.options.KeepAlive) {
    opt.forever = true;
}
```
已定位原因，是因为默认 KeepAlive 导致问题，可临时制定 new COS({KeepAlive: false}); 规避问题。
我们另外确认修复方案。

**Comment by lyswhut** [comment]
上述问题加了`KeepAlive: false`后已正常工作。

还有个疑问，上传文件时`onHashProgress`回调似乎从来都没有被触发过，以下是测试代码：
```js
cos.sliceUploadFile({
  Bucket: config.bucket,
  Region: config.region,
  Key: config.prefix + fileName,
  FilePath: filePath,
  onHashProgress(progressData) {
    console.log('校验', JSON.stringify(progressData))
  },
  onProgress(progressData) {
    console.log('上传', JSON.stringify(progressData))
  },
}, (err, data) => {
  if (err) {
    console.log(err)
    return reject(err)
  }
  resolve(data)
})
```
输出的Log：
![20190720114032](https://user-images.githubusercontent.com/20365169/61573600-ff5b9180-aae3-11e9-887c-3563caaa907b.png)
可以看到上传任务被创建时，`onHashProgress`从来没有被执行过。

**Comment by carsonxu** [comment]
上传过一部分，续传会检验已传分片，才会有这个进度。

**Comment by carsonxu** [comment]
version 2.5.12 fixed
