### ISSUE TITLE
nuxt  引入报错找不到fs

### ISSUE THREAD

**Issue by yangfan-coder** [tencentyun/cos-nodejs-sdk-v5#72]
![image](https://user-images.githubusercontent.com/14069048/69127442-328b4d00-0ae5-11ea-8ca3-f18dfa2ea285.png)

**Comment by carsonxu** [comment]
nuxt 建议用 script 标签格式引入 cos js sdk：
https://github.com/tencentyun/cos-js-sdk-v5

**Comment by yangfandashuaige** [comment]
> nuxt 建议用 script 标签格式引入 cos js sdk：
> https://github.com/tencentyun/cos-js-sdk-v5
为啥？ SDK引入的时候还是有问题的！？没有好的解决方案吗？

**Comment by carsonxu** [comment]
1. nuxt 我理解是服务端渲染，里面用到 JS 上传逻辑应该要在浏览器执行，需要用 cos-js-sdk-v5。
cos-nodejs-sdk-v5 是在服务端执行。
2. 没针对 nuxt 场景做过测试，但 script 方式引入 [tencentyun/cos-js-sdk-v5](https://github.com/tencentyun/cos-js-sdk-v5) 应该能正常用。

**Comment by yangfandashuaige** [comment]
> 1. nuxt 我理解是服务端渲染，里面用到 JS 上传逻辑应该要在浏览器执行，需要用 cos-js-sdk-v5。
>    cos-nodejs-sdk-v5 是在服务端执行。
> 2. 没针对 nuxt 场景做过测试，但 script 方式引入 [tencentyun/cos-js-sdk-v5](https://github.com/tencentyun/cos-js-sdk-v5) 应该能正常用。
但是我们是SPA渲染的也就是单页面 还是不行 目前我们在当前的组件引入 项目直接起不来
可有解决的方法

**Comment by carsonxu** [comment]
这个问题解决了吗？

**Comment by yangfandashuaige** [comment]
可以了 在打包的时候引入就好 之前怎么解决 我也忘了

**Comment by carsonxu** [comment]
https://github.com/tencentyun/cos-js-sdk-v5/issues/84
已有解决方案。
