### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by chase-lou** [tencentyun/cos-nodejs-sdk-v5#73]
当上传文件并发数大于1时，会出现这个错误
简单上传，文件小于1M

**Comment by carsonxu** [comment]
new COS() 时，有个 KeepAlive 参数看看设置为 false 试试

**Comment by Spectrumleeee** [comment]
var cos = new COS({
    SecretId: config.QCLOUD_SECRET_ID,
    SecretKey: config.QCLOUD_SECRET_KEY,
    KeepAlive: false
})

module.exports.upload = function (filePathIn, fileName, groupName, applicationBucketName) {
    var bucketName = applicationBucketName || config.QCLOUD_BUCKET_NAME;
    bucketName = bucketName + "-" + config.QCLOUD_APP_ID;
    fileName = normalizeFileName(fileName);
    var ext = path.extname(fileName);
    var base = path.basename(fileName, ext);
    fileName = base + '-' + uuid.v1() + ext;
    // 分片上传
    return new Promise(function(resolve, reject) {
        utils.info('upload start ');
        cos.sliceUploadFile({
            Bucket: bucketName, // Bucket 格式：test-1250000000
            Region: 'ap-shanghai',
            Key: fileName,
            FilePath: filePathIn
        }, function (err, data) {
            utils.info(err);
            utils.info(data);
            console.log(err, data);
            if (data.statusCode === 200) {
                resolve(JSON.stringify({
                    url: config.PRODUCTION === true ? 'https://' + data.Location : 'http://' + data.Location,
                    path: data.Key
                }));
            } else {
                reject(data);
            }
        });
    });
}

cos-nodejs-sdk-v5@2.6.2 
在开发环境可以正常上传，
测试环境返回的err为 ECONNRESET，data为空，
初步排查测试网络都是OK的
ping service.cos.myqcloud.com 
ping clickeggs-dev-10081362.cos.ap-shanghai.myqcloud.com

请问这个大概是什么原因，网上大部分说是网络权限，的确我们测试环境部分受限，但是sdk用的域名都可以ping通的

**Comment by Spectrumleeee** [comment]
> ```
> var cos = new COS({
>     SecretId: config.QCLOUD_SECRET_ID,
>     SecretKey: config.QCLOUD_SECRET_KEY,
>     KeepAlive: false
> })
> 
> module.exports.upload = function (filePathIn, fileName, groupName, applicationBucketName) {
>     var bucketName = applicationBucketName || config.QCLOUD_BUCKET_NAME;
>     bucketName = bucketName + "-" + config.QCLOUD_APP_ID;
>     fileName = normalizeFileName(fileName);
>     var ext = path.extname(fileName);
>     var base = path.basename(fileName, ext);
>     fileName = base + '-' + uuid.v1() + ext;
>     // 分片上传
>     return new Promise(function(resolve, reject) {
>         utils.info('upload start ');
>         cos.sliceUploadFile({
>             Bucket: bucketName, // Bucket 格式：test-1250000000
>             Region: 'ap-shanghai',
>             Key: fileName,
>             FilePath: filePathIn
>         }, function (err, data) {
>             console.log(err, data);
>             if (data.statusCode === 200) {
>                 resolve(JSON.stringify({
>                     url: config.PRODUCTION === true ? 'https://' + data.Location : 'http://' + data.Location,
>                     path: data.Key
>                 }));
>             } else {
>                 reject(data);
>             }
>         });
>     });
> }
> ```
> 
> cos-nodejs-sdk-v5@2.6.2
> 在开发环境可以正常上传，
> 测试环境返回的err为 ECONNRESET，data为空，
> 初步排查测试网络都是OK的
> ping service.cos.myqcloud.com
> ping clickeggs-dev-10081362.cos.ap-shanghai.myqcloud.com
> 
> 请问这个大概是什么原因，网上大部分说是网络权限，的确我们测试环境部分受限，但是sdk用的域名都可以ping通的

DONE，closed~
