### ISSUE TITLE
模块加载过慢

### ISSUE THREAD

**Issue by wangkunmeng** [tencentyun/cos-nodejs-sdk-v5#74]
``` js
console.time('cos');
console.time('cos-nodejs-sdk-v5');
const COS = require('cos-nodejs-sdk-v5');
console.timeEnd('cos-nodejs-sdk-v5');
console.time('qcloud-cos-sts');
const STS = require('qcloud-cos-sts');
console.timeEnd('qcloud-cos-sts');
console.timeEnd('cos');
// cos-nodejs-sdk-v5: 5305.209ms
// qcloud-cos-sts: 57.109ms
// cos: 5399.677ms
```
**这是ping了一下腾讯域名么...加载这么慢**

**Comment by carsonxu** [comment]
我这里测试是：
cos-nodejs-sdk-v5 
xml2js 49ms
configstore 43ms
request 135ms
感觉是最后这两个最后两个做了一些事情。你看看确认下你环境。
你的业务对加载时间敏感吗？

**Comment by wangkunmeng** [comment]
@carsonxu 云服务器上时间挺短的，本地vagrant启动2核2G的虚拟机比较慢，会造成数据库连接超时
cos-nodejs-sdk-v5: 134.005ms
qcloud-cos-sts: 0.810ms
cos: 135.102ms

**Comment by wangkunmeng** [comment]
调查虚拟机中cos-nodejs-sdk-v5中加载request模块耗时3秒多，建议替换为axios

**Comment by byteluo** [comment]
感觉第一次发请求会卡0.1s，之后就好了，好玄👀
