### ISSUE TITLE
自带的多块上传方法sliceUploadFile为什么设计成FIle模式而不是Stream模式？

### ISSUE THREAD

**Issue by oneWalker** [tencentyun/cos-nodejs-sdk-v5#75]
从腾讯云自带的方法来看：
分片上传，仍然是file模式下，进行上传，而不是stream模式？

**Comment by carsonxu** [comment]
stream 模式建议使用 putObject，sliceUploadFile 没支持 stream 原因：
1. stream 转为多个分片上传逻辑会变得复杂很多。
2. 只传流，某些动作不好处理，比如：没传入文件大小，就不好指定恰当的分片大小；不好做 md5 计算。
后续有考虑单独一个方法支持流式分片上传。

**Comment by oneWalker** [comment]
嗯嗯，了解了。我用里面改写的流上传简单实现了下流式上传；
 async stream_uploader(stream, key) {
        return new Promise((resolve, reject) => {
          // 腾讯云 文件上传
          let params = {
            Bucket: this.options.Bucket,                         
            Region: this.options.Region,                         
            Key: key,                                           
            Body: stream,                                       
            ContentLength: stream._readableState.length
          }
          // console.log(params)
          this.cos.putObject(params, function(err, data) {
            sendToWormhole(stream)
            if(err) {
              return reject(err)
            } else {
              return resolve(data)
            }
          })
        })
    }
