### ISSUE TITLE
Compiled err

### ISSUE THREAD

**Issue by chenny** [tencentyun/cos-nodejs-sdk-v5#81]
WARNING  Compiled with 1 warnings                                                                                                                                                                              10:59:04 AM

 warning  in ./node_modules/write-file-atomic/index.js

Module not found: Error: Can't resolve 'worker_threads' in '/Users/chenny/Documents/iruidao/client_oa2/node_modules/write-file-atomic'

**Comment by carsonxu** [comment]
nodejs 什么版本？

**Comment by chenny** [comment]
谢谢已经接了. 安装了 node 版本 应该安装 js 版本

cos-nodejs-sdk-v5 换成 
cos-js-sdk-v5

**Comment by carsonxu** [comment]
谢谢反馈
