### ISSUE TITLE
是否有获取“访问路径列表”的API

### ISSUE THREAD

**Issue by willnewii** [tencentyun/cos-nodejs-sdk-v5#82]
腾讯云子账号有一种通过添加访问路径的方式访问存储桶。

我看腾讯云官方的COSBrowser也支持该方式，默认能读取出访问路径列表。不知道有没有相关的API？看文档是没有找到相关资料。

**Comment by carsonxu** [comment]
暂时没对外提供。

**Comment by willnewii** [comment]
了解。
