### ISSUE TITLE
sliceUploadFile 上传文件多丢失问题

### ISSUE THREAD

**Issue by Dd-ouni** [tencentyun/cos-nodejs-sdk-v5#83]
并没有抛出错误信息。但是云cdn的目录下找不到文件

**Comment by carsonxu** [comment]
具体点是怎么丢失？

**Comment by Dd-ouni** [comment]
> 具体点是怎么丢失？

sliceUploadFile api 得到的信息是上传成功了， cdn 目录下面却找不到文件，减少上传文件就不会出现这个问题。

**Comment by carsonxu** [comment]
建议提工单排查。
