### ISSUE TITLE
getBucket 使用有问题

### ISSUE THREAD

**Issue by nlbydcg** [tencentyun/cos-nodejs-sdk-v5#84]
当我使用getBucket的时候
![image](https://user-images.githubusercontent.com/40027034/88786121-b04f3e80-d1c4-11ea-9cb8-50ff6a82f64e.png)
有的有文件夹路径没有列出来
basic/3761949F905E0534/basic/3761949F905E0534/  
查询出来的结果并没有
但是 basic/3761949F905E0534/basic/111/test/ 这个文件夹路径列出来了
一样给出来一个文件夹的数据
是因为地址重复导致的这个问题么？？
我查询的的是
basic/3761949F905E0534/这个地址路径下的文件和文件夹

**Comment by carsonxu** [comment]
1. 在控制台、cosbrowser 操作“新建文件夹”，就会创建一个空的 / 结尾的 Object 用于占位。这样里面没文件也可以表示有这个文件夹。
2. 通过 API、SDK 上传文件或文件夹，一般就不会创建这个文件夹。
