### ISSUE TITLE
云上处理图片接口

### ISSUE THREAD

**Issue by tbto** [tencentyun/cos-nodejs-sdk-v5#92]
https://cloud.tencent.com/document/product/436/47222#.E5.AF.B9.E4.BA.91.E4.B8.8A.E6.95.B0.E6.8D.AE.E8.BF.9B.E8.A1.8C.E5.9B.BE.E7.89.87.E5.A4.84.E7.90.86
能否参考.net的sdk实现一下云上处理图片的接口，或者将相关的方法开放出来，由使用者来自定义实现也行（或者目前本身就能够自定义，还请指教一下）
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/3437980/100054696-87327800-2e5d-11eb-8b15-e795e406fefd.png">

**Comment by tbto** [comment]
类似下面截图示例的逻辑代码，看能否添加该方法。建议把submitRequest开放出来，方便使用者自定义扩展。
![image](https://user-images.githubusercontent.com/3437980/100068299-501a9180-2e72-11eb-9f91-80965c2fefe2.png)

**Comment by livehigh** [comment]
> 类似下面截图示例的逻辑代码，看能否添加该方法。建议把submitRequest开放出来，方便使用者自定义扩展。 ![image](https://user-images.githubusercontent.com/3437980/100068299-501a9180-2e72-11eb-9f91-80965c2fefe2.png)

感谢反馈
目前已实现云上图片处理，参考文档：https://cloud.tencent.com/document/product/436/55332
新版本已开放cos.request()方法，可参考demo进行自定义扩展。
