### ISSUE TITLE
大兄弟们

### ISSUE THREAD

**Issue by Erchoc** [tencentyun/cos-nodejs-sdk-v5#95]
求求你别更新 cos-nodejs-sdk-v5 这个库了行吗？

美其名曰优化代码，我最近更新 yarn.lock，发现你们最近一个月的 d.ts 声明文件吓鸡儿乱写。上个版本 getAuth 的声明类型写的是对的，现在最新的 2.9.1 又被你们改回去错的。这不是瞎搞吗？？？能少一点 breakchange 吗！！！

**Comment by carsonxu** [comment]
getAuth 的声明类型，是否指 getAuthorization 的回传参数 SecurityToken 的改动？

**Comment by Erchoc** [comment]
> getAuth 的声明类型，是否指 getAuthorization 的回传参数 SecurityToken 的改动？

我就是吐槽一下你们的声明文件，发布不够严谨，别太较真。

**Comment by carsonxu** [comment]
v2.9.2 优化了 SecurityToken 的改动，兼容老的格式。
