### ISSUE TITLE
如何生成整个 Bucket 的签名？

### ISSUE THREAD

**Issue by minetsh** [tencentyun/cos-nodejs-sdk-v5#98]
`getObjectUrl` 必须要给 Key 值，如何才能拿到整个 Bucket 的签名？

**Comment by carsonxu** [comment]
不支持，不同文件要用不同文件名。
具体什么场景？一个临时密钥可以授权一个存储桶任意文件。但是在用的时候要算签名。

**Comment by minetsh** [comment]
客户端需要展示各种私有图片，返回的地址都是原始的，不带签名的，客户端在展示时临时拼上签名，如果每次都不一样代价太大，我记得V2还是更早的版本是支持的应该，所以现在这个方式没法升级的V5了。

**Comment by livehigh** [comment]
不支持
